# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cb89b0878df105d0d09c8ab19be7e169"
name = "test-app"
handle = "test-app-10324"
application_url = "https://candidate-profits-trials-replication.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9aeae7d7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://candidate-profits-trials-replication.trycloudflare.com/auth/callback",
  "https://candidate-profits-trials-replication.trycloudflare.com/auth/shopify/callback",
  "https://candidate-profits-trials-replication.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://localhost:57221"

[pos]
embedded = false
